import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen flex flex-col overflow-x-hidden`}
      >
        <div className="flex flex-col w-full">
          <h1 className="text-4xl font-bold text-center mt-10">
            Predictive CMI
          </h1>
          <p className="text-sm text-muted-foreground text-center px-8">
            Predicción de Ventas, Beneficios e Ingresos Totales
          </p>
          {children}
        </div>

        <footer>
          <div className="flex justify-center items-center gap-2 mt-auto p-4">
            <p className="text-sm text-muted-foreground">
              © 2025 Predictive CMI. Todos los derechos reservados.
            </p>
            <p className="text-muted-foreground">
              Creado por Yoannis Sánchez Soto & Yisel Pupo Batista{" "}
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
